networks:
  dls-service:
    driver: bridge

services:
  broker0:
    image: apache/kafka:latest
    container_name: broker
    networks:
      - dls-service
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: BOB://broker0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: BOB://broker0:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BOB:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: BOB
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3


  consumer1:
    build:
      context: ./consumer
    restart: on-failure:5
    container_name: consumer1
    command: python ES_api.py
    depends_on:
      - broker0
    networks:
      - dls-service
    environment:
      - KAFKA_BROKER=broker0:9092

